### ISSUE TITLE
New option "Mobile sensor" for agents with GPS on board. 

### ISSUE THREAD

**Issue by ensrationis** [airalab/sensors-connectivity#2]
To support R&D in St. Petersburg with marine vessels in canals, we need to have option in [configuration file](https://github.com/airalab/sensors-connectivity/blob/master/config/default.yaml) with name  "Mobile sensor". When "Mobile sensor" option switch on then sensor should have possibility for real time updating of geo position.

**Comment by tubleronchik** [comment]
For mobile sensor should be used model [3](https://github.com/airalab/sensors-connectivity/blob/master/connectivity/src/drivers/sds011.py#L12)
