### ISSUE TITLE
Размножение точек на карте

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors-connectivity#25]
![Размножение точек](https://user-images.githubusercontent.com/77608670/104920725-a9ee9200-59b1-11eb-8f91-15db5ba92dcc.png)
При длительном экспонировании на одной геометке начинает мультиплицироваться точка с данными. Причем в каждой из подточек единичные показатели
![Размножение точек2](https://user-images.githubusercontent.com/77608670/104920889-efab5a80-59b1-11eb-8ade-a4e2e5656fac.png)

**Comment by Vourhey** [comment]
Fixed in #31
