### ISSUE TITLE
IoT Connectivity over TCP

### ISSUE THREAD

**Issue by ensrationis** [airalab/sensors-connectivity#3]
We need to have approach where Aira agent can use telemetry from remote sensors. First step on this way is to use esp8266 board on sensor side . In this case we can use mobile internet connection and send data from sensor to telemetry agent over TCP.

**Comment by akru** [comment]
What’s about technical specification here?

* OSI protocol parameters
* Codecs
* Communication schemes

**Comment by ensrationis** [comment]
> What’s about technical specification here?
> 
>     * OSI protocol parameters
> 
>     * Codecs
> 
>     * Communication schemes

@Vourhey  when you will make release - pls use akru specification.

**Comment by Vourhey** [comment]
Implemented in release v0.2
