### ISSUE TITLE
IoT Connectivity over LoRa

### ISSUE THREAD

**Issue by ensrationis** [airalab/sensors-connectivity#4]
LoRa is very popular IoT protocol and after we will finished with [IoT Connectivity over TCP](https://github.com/airalab/sensors-connectivity/issues/3) next right step i think will be to support LoRa to connect remote sensor with Aira telemetry agent.

**Comment by akru** [comment]
So, LoraWan provides TCP/IP like functionality: https://www.thethingsnetwork.org/docs/lorawan/architecture.html

I guess it could be used for quick solve this issue.

**Comment by tubleronchik** [comment]
for future implementation
