### ISSUE TITLE
Collect and send asynchronous 

### ISSUE THREAD

**Issue by ensrationis** [airalab/sensors-connectivity#6]
Now, we have [read-interval parameter in config/default.yaml](https://github.com/airalab/sensors-connectivity/blob/master/config/default.yaml#L5). Can we add one more specific parameter with name "broadcast-interval", which will response to frequency of publishing data in realtime / IPFS pubsub data exchange channels?

**For example:**
read-interval: 300    # time between two measurements in seconds
broadcast-interval: 10 # time between two broadcast actions in seconds

P.S.: dump-interval - good name for this parameter @Vourhey ! :)

**Comment by Vourhey** [comment]
Implemented in release v0.2
