### ISSUE TITLE
Particulate matter sensor does not push data to Influxdb

### ISSUE THREAD

**Issue by v0r0n0v** [airalab/sensors-connectivity#86]
**Describe the error**

What I have:
1.ESP8266

Particulate matter sensor

ID: 5234708 (dc4f224fe014)
Firmware version: R_2022-137/EN (Jul 3 2023)

Firmware version

R_2022-137
ST:1
SDK:2.2.2-dev(38a443e)
Core:2.7.3-3-g2843a5ac=20703003
lwIP:STABLE-2_1_2_RELEASE
glue:1.2-30-g92add50
BearSSL:5c771be

2. SDS011
3.BME280
4. Own database influxdb version influxdb: 2.0

Problem:
I don’t see any data coming into the influx db database from the ESP8266

**For playback**

(I log in using my login password successfully through the web interface)
influxdb version:2.0
ifluxdb authorization data:
login: sysadmin
password: sysadmin
database: sysadmin
ip: 17.0.0.200
port: 8086

1. Port 8086 is open on the server
2. The database has a sysadmin database
3. Authorization is allowed from the sysadmin user (the user has full access rights)
4. In ESP8266 configuration parameters
The Send data to influxdb checkbox is checked below what data I enter

server: 17.0.0.200
path: /write?db=sysadmin
user: sysadmin
password: sysadmin
measurement: feinstaub

**Expected Behavior**

The goal is to get data from ESP8266 into the influxdb database,
to later display graphs in grafana

**Screenshots**

<a href="https://imgbb.com/"><img src="https://i.ibb.co/tQybdJW/1.png" alt="1" border="0"></a>

<a href="https://imgbb.com/"><img src="https://i.ibb.co/xgS93p7/2.png" alt="2" border="0"></a>

<a href="https://ibb.co/jhY1jp6"><img src="https://i.ibb.co/VVGPkKj/3.png" alt="3" border="0"></a>

<a href="https://ibb.co/ZYJx4Nx"><img src="https://i.ibb.co/TbTtjrt/4.png" alt="4" border="0"></a>

**Additional context**
Please help me solve this problem,
Perhaps I'm not writing the request to transfer data to the database correctly?

path: /write?db=sysadmin

if so, which one is correct?
I tried to find information on the Internet, but didn’t find anything useful.
I see that the problem is not only with me and other users. Please help me solve this problem
Thanks for understanding

**Comment by tubleronchik** [comment]
I close this issue since it's not related to our project.
